# This is a basic workflow to help you get started with Actions

name: Build static site

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true

    # Download Hugo binary
    - name: Download Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.70.0'
        extended: true
        
    # Build the site using Hugo
    - name: Run hugo build
      run: |
        hugo version
        hugo --destination docs
      
    # Commits the built site to the repository
    - name: Run a multi-line script
      uses: EndBug/add-and-commit@v4
      with:
        message: "Update site build"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
